### ISSUE TITLE
文档预览问题

### ISSUE THREAD

**Issue by lvfangren** [qiqi-1996/qi-design-vue#2]
问题一： 底部的暗夜模式，应用主题切换存在BUG，当从默认的暗夜切换到白天时，点击按钮触发一定的时间会弹起I can’t breathe.的toast，且一切选择会变成默认的值。

解决：注释掉store.js文件中ICantBreathe方法的执行

问题二： 主题切换时，例如从暗夜切到白天，但是还是文案没有发生变化；可以更改吗还是？

问题三：选择完应用主题后，再次展开选项框，没有一个选中效果，感觉可以加下，应该会对用户更友好。 

![image](https://user-images.githubusercontent.com/25928863/85220547-e1c33600-b3de-11ea-96cd-3351e19f78c0.png)

我想尝试做下上面的修改，但是不知道您是否有解决这些问题或者接受pr？

**Comment by SaekiRaku** [comment]
1. `I Can't Breathe` 是故意加上的，如果影响体验，我试着改进一下呈现方式。
2. 的确是个细节问题，我马上修改。
3. 此处是最开始的一个遗留组件，准备废弃这个选择框组件，改成其他的。

**Comment by lvfangren** [comment]
👏

**Comment by lvfangren** [comment]
是否可以在控制台埋下一个彩蛋，显示当前版本和构建时间等信息。感觉有趣😂

**Comment by SaekiRaku** [comment]
@lvfangren 抱歉，图片太大了，没注意到图片最后面的 PR 请求。我很乐意接收 PR，但是目前的主要问题是代码和结构还不太规范。比如目前文档的  i18n 只进行了一半，而另一半的代码是之前没有考虑 i18n 而写的，所以需要很繁琐的复制粘贴工作。也因此不太好整理 PR 规范，可能会影响合作效率。我目前也在探索更好的协作方式。

**Comment by lvfangren** [comment]
@SaekiRaku S 我认同这个作品。也会持续关注进展，后面如果有好的机会也希望能为这个作品进行贡献。（话说vscode-rainbow-fart很有意思😂）
