### ISSUE TITLE
文档无法访问

### ISSUE THREAD

**Issue by Guo-Zhang** [qiqi-1996/qi-design-vue#36]
https://qiqi-1996.github.io/qi-design-vue/

页面上只有一个“I can't breath”

**Comment by SaekiRaku** [comment]
感谢反馈，工作太忙，这个仓库暂时不维护了。应该是文档上 CDN 加载的 Vue 库没锁版本导致的。

**Comment by Guo-Zhang** [comment]
感谢回复，我是从vscode-rainbow-fart项目看到它的。我注意到UI页面的效果非常不错，也在源码里看到了Sketch文件。因此好奇心驱使让我看了看这个项目，想学习下设计和前端经验。我可以自己看文档源码。
